alias: landing Button 1 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.landing_switch
    scene_id: 14
action:
  - service: notify.notify
    data:
      message: "landing Button 1 Double"
      title: "Button!"
  - service: light.toggle
    entity_id: light.stair_lights
