alias: bedroom_4 Button 1 Release
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.bedroom_4_switch
    scene_id: 13
action:
  service: notify.notify
  data:
    message: "bedroom_4 Button 1 Release"
    title: "Button!"
