alias: "Flic black Single"
trigger:
  platform: event
  event_type: flic_click
  event_data:
    button_name: flic_80e4da7291ec
    click_type: single
action:
  service: notify.notify
  data:
    message: "Flic black Single"
    title: "Button!"
