alias: Kitchen Rear Button 2 Double
trigger:
  platform: event
  event_type: ozw.scene_activated
  event_data:
    node_id: 4
    scene_id: 24
action:
  - service: light.toggle
    entity_id: light.external_rear
