alias: kitchen_rear Button 2 Hold
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.kitchen_rear
    scene_id: 22
action:
  service: notify.notify
  data:
    message: "kitchen_rear Button 2 Hold"
    title: "Button!"
