alias: kitchen_rear Button 2 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.kitchen_rear
    scene_id: 26
action:
  - service: light.toggle
    entity_id: light.lounge