alias: kitchen_rear Button 2 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.kitchen_rear_switch
    scene_id: 24
action:
  service: notify.notify
  data:
    message: "kitchen_rear Button 2 Double"
    title: "Button!"
