# Implicitly attached to toggle bedroom 3 ceiling
alias: bedroom_3 Button 1 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.bedroom_3
    scene_id: 16
action:
  service: notify.notify
  data:
    message: "bedroom_3 Button 1 Single"
    title: "Button!"
