
sensor.fibaro_system_fgd212_dimmer_2_*:
  ignored: true
  polling_intensity: 0
sensor.steinel_is140_2_sourcenodeid*:
  ignored: true
  polling_intensity: 0
sensor.steinel_is140_2_alarm_level*:
  ignored: true
  polling_intensity: 0
sensor.steinel_is140_2_alarm_type*:
  ignored: true
  polling_intensity: 0
sensor.steinel_is140_2_system*:
  ignored: true
  polling_intensity: 0
switch.steinel_is140_2_switch*:
  ignored: true
  polling_intensity: 0
