alias: office Button 2 Release
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.office_switch
    scene_id: 23
action:
  service: notify.notify
  data:
    message: "office Button 2 Release"
    title: "Button!"
