alias: "Flic green Double"
trigger:
  platform: event
  event_type: flic_click
  event_data:
    button_name: flic_80e4da72b83e
    click_type: double
action:
  service: notify.notify
  data:
    message: "Flic green Double"
    title: "Button!"
