alias: Master Bedroom Button 2 Double
trigger:
  platform: event
  event_type: zwave_mqtt.scene_activated
  event_data:
    node_id: "{{ state_attr('light.bedroom_master', 'node_id') }}"
    scene_id: 24
action:
  - service: fan.toggle
    entity_id: fan.ensuite_extractor
