alias: Master Bedroom Button 2 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.master_bedroom
    scene_id: 24
action:
  - service: fan.toggle
    entity_id: fan.ensuite_extractor

