alias: master_bedroom Button 2 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.master_bedroom
    scene_id: 24
action:
  service: notify.notify
  data:
    message: "master_bedroom Button 2 Double"
    title: "Button!"
