alias: master_bedroom Button 2 Hold
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.master_bedroom_switch
    scene_id: 22
action:
  service: notify.notify
  data:
    message: "master_bedroom Button 2 Hold"
    title: "Button!"
