alias: Master Bedroom Button 2 Single
trigger:
  platform: event
  event_type: ozw.scene_activated
  event_data:
    node_id: 21
    scene_id: 26
action:
  - service: light.toggle
    entity_id: light.ensuite
