alias: Master Bedroom Button 2 Single
trigger:
  platform: event
  event_type: zwave_mqtt.scene_activated
  event_data:
    node_id: "{{ state_attr('light.bedroom_master', 'node_id') }}"
    scene_id: 26
action:
  - service: light.toggle
    entity_id: light.ensuite
