# Linked to a zwave group to toggle ensuite ceiling
alias: master_bedroom Button 2 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.master_bedroom
    scene_id: 26
action:
  - service: notify.notify
    data:
      message: "master_bedroom Button 2 Single"
      title: "Button!"