alias: Friday Shabbat Prep Lights on
trigger:
  platform: sun	
  event: sunset
  offset: '-00:45:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday: 
       - fri
action:
  service: script.turn_on
  entity_id: script.friday_night_prep
