alias: Friday Shabbat Prep Lights on
trigger:
  platform: sun
  event: sunset
  offset: "-00:45:00"
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - fri
action:
  - service: light.turn_on
    data:
      entity_id:
        - light.kitchen_worktop
        - light.kitchen_ceiling
        - light.kitchen_island
        - light.lounge
        - light.playroom
        - light.matans_bedroom
        - light.bedroom_master
        - light.ensuite
        - light.bathroom
        - light.toilet
        - light.landing
        - light.hall
      brightness: 255
  - service: light.turn_on
    entity_id: light.stairs
