alias: Friday Shabbat In Lights on
trigger:
  - platform: state
    entity_id: binary_sensor.shabbat
    from: "off"
    to: "on"
action:
  - service: light.turn_on
    data:
      entity_id:
        - light.kitchen_ceiling
        - light.lounge
        #        - light.playroom
        - light.ensuite
        - light.bathroom
        - light.toilet
        - light.hall
      brightness: 255
  #  - service: light.turn_on
  #    entity_id: light.stairs
  - service: light.turn_off
    data:
      entity_id:
        - light.kitchen_worktop
        - light.kitchen_island
        - light.bedroom_matan
        - light.bedroom_master
        - light.bedroom_3
        - light.aris_bedroom
        - light.landing
        - light.lamp
