alias: Friday Night All Off
trigger:
  - platform: time
    at: "23:59:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: "binary_sensor.shabbat"
      state: "on"
action:
  - service: light.turn_off
    entity_id:
      - light.kitchen_worktop
      - light.kitchen_ceiling
      - light.kitchen_island
      - light.lounge
      - light.playroom
      - light.matans_bedroom
      - light.bedroom_master
      - light.aris_bedroom
      - light.ensuite
      - light.bathroom
      - light.toilet
      - light.landing
      - light.hall
