alias: Friday Night All Off
trigger:
  - platform: time
    at: "23:59:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: "binary_sensor.shabbat"
      state: "on"
action:
  - service: light.turn_off
    entity_id:
      - light.kitchen_worktop
      - light.kitchen_ceiling
      - light.kitchen_island
      - light.lounge
      - light.playroom
      - light.bedroom_matan
      - light.bedroom_master
      - light.bedroom_ari
      - light.toilet
      - light.landing
      - light.hall
      - light.utility
  - delay: '00:01:30'
  - service: light.turn_off
    entity_id:
      - light.kitchen_worktop
      - light.kitchen_ceiling
      - light.kitchen_island
      - light.lounge
      - light.playroom
      - light.bedroom_matan
      - light.bedroom_master
      - light.bedroom_ari
      - light.toilet
      - light.landing
      - light.hall
      - light.utility
