alias: Overnight Bathroom Dim
trigger:
  - platform: time
    at: "00:00:01"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: "binary_sensor.shabbat"
      state: "on"
action:
  - service: light.turn_on
    entity_id:
      - light.bathroom
      - light.ensuite
      - light.bedroom_spare
    data:
      brightness: 2
