alias: Shabbat Morning Lights on
trigger:
  - platform: time
    at: "06:00:00"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: "binary_sensor.shabbat"
      state: "on"
action:
  - service: light.turn_on
    entity_id:
      - light.utility
      - light.ensuite
      - light.playroom
      - light.lounge
      - light.kitchen_ceiling
