alias: Shabbat sunrise lights off
trigger:
  platform: sun
  event: sunrise
  offset: '+00:59:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - sat
action:
  - service: light.turn_off
    entity_id:
      - group.all_lights
  - service: light.turn_on
    entity_id:
      - light.ensuite
      - light.utility