alias: Shabbat sunrise lights off
trigger:
  platform: sun
  event: sunrise
  offset: '+00:30:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - sat
action:
  service: light.turn_off
  entity_id:
    - group.all_lights