alias: Shavua Tov
trigger:
  - platform: state
    entity_id: binary_sensor.shabbat
    from: 'on'
    to: 'off'
action:
  - service: light.turn_on
    data:
      entity_id:
        - light.lamp
#        - light.matans_kitchen
      brightness: 255
      color_name: purple
  - service: light.turn_on
    entity_id:
      - light.stairs