alias: Reset Bathroom Brightness
trigger:
  - platform: state
    entity_id: binary_sensor.shabbat
    from: 'on'
    to: 'off'
action:
  - service: light.turn_on
    data:
      entity_id:
        - light.ensuite
        - light.bathroom
      brightness: 255
  - service: 
  - delay:
      minutes: 10
  - service: light.turn_off
    entity_id:
      - light.ensuite
      - light.bathroom