# Implicitly attached to toggle kitchen rear ceiling
alias: kitchen_rear Button 1 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.kitchen_rear
    scene_id: 16
action:
  service: notify.notify
  data:
    message: "kitchen_rear Button 1 Single"
    title: "Button!"
