alias: kitchen Button 1 Release
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.kitchen
    scene_id: 13
action:
  service: notify.notify
  data:
    message: "kitchen Button 1 Release"
    title: "Button!"
