alias: matans_bedroom Button 1 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.matans_bedroom_switch
    scene_id: 16
action:
  service: notify.notify
  data:
    message: "matans_bedroom Button 1 Single"
    title: "Button!"
