alias: bedroom_4 Button 2 Hold
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.bedroom_4_switch
    scene_id: 22
action:
  service: notify.notify
  data:
    message: "bedroom_4 Button 2 Hold"
    title: "Button!"
