alias: toilet Button 1 Hold
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.toilet_switch
    scene_id: 12
action:
  service: notify.notify
  data:
    message: "toilet Button 1 Hold"
    title: "Button!"
