# Implicitly attached to toggle toilet ceiling
alias: toilet Button 1 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.toilet_switch
    scene_id: 16
action:
  service: notify.notify
  data:
    message: "toilet Button 1 Single"
    title: "Button!"
