alias: "Dash Duracell"
trigger:
  platform: state
  entity_id: binary_sensor.dash_duracell
  to: 'on'
action:
  - service: notify.notify
    data:
      message: "Dash Duracell"
      title: "Button!"