alias: "Dash Water Wipes"
trigger:
  platform: state
  entity_id: binary_sensor.dash_water_wipes
  to: 'on'
action:
  - service: notify.notify
    data:
      message: "Dash Water Wipes"
      title: "Button!"