alias: "Dash Wilkinson Sword"
trigger:
  platform: state
  entity_id: binary_sensor.dash_wilkinson_sword
  to: 'on'
action:
  - service: notify.notify
    data:
      message: "Dsah Wilkinson Sword"
      title: "Button!"