alias: "Flic white Single"
trigger:
  platform: event
  event_type: flic_click
  event_data:
    button_name: flic_80e4da72aafa
    click_type: single
action:
  service: notify.notify
  data:
    message: "Flic white Single"
    title: "Button!"
