alias: hall Button 2 Double
trigger:
  platform: event
  event_type: zwave_mqtt.scene_activated
  event_data:
    node_id: "{{ state_attr('light.hall', 'node_id') }}"
    scene_id: 24
action:
  - service: light.toggle
    entity_id: light.stairs
