alias: hall Button 2 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.hall
    scene_id: 24
action:
  - service: notify.notify
    data:
      message: "hall Button 2 Double"
      title: "Button!"
  - service: light.toggle
    entity_id: light.stair_lights