alias: hall Button 1 Double
trigger:
  platform: event
  event_type: ozw.scene_activated
  event_data:
    node_id: 7
    scene_id: 14
action:
  - service: light.toggle
    entity_id: light.front_door
