alias: hall Button 1 Hold
trigger:
  platform: event
  event_type: zwave_mqtt.scene_activated
  event_data:
    node_id: 7
    scene_id: 12
action:
  - service: light.turn_off
    entity_id: group.all_lights
  - service: fan.turn_off
    entity_id: group.all_fans
