alias: hall Button 1 Hold
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.hall
    scene_id: 12
action:
  - service: notify.notify
    data:
      message: "hall Button 1 Hold"
      title: "Button!"
#  - service: # turn off all lights & fans