alias: Utility Button 1 Double
trigger:
  platform: event
  event_type: zwave_mqtt.scene_activated
  event_data:
    node_id: "{{ state_attr('light.utility', 'node_id') }}"
    scene_id: 14
action:
  - service: fan.toggle
    entity_id: fan.utility_extractor
