# Implicitly attached to toggle ensuite ceiling
alias: ensuite Button 1 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.ensuite_switch
    scene_id: 16
action:
  service: notify.notify
  data:
    message: "ensuite Button 1 Single"
    title: "Button!"
