alias: "Flic Turquoise Double"
trigger:
  platform: event
  event_type: flic_click
  event_data:
    button_name: flic_80e4da72aba3
    click_type: double
action:
  service: notify.notify
  data:
    message: "Flic Turquoise Double"
    title: "Button!"
