alias: "Flic Turquoise Single"
trigger:
  platform: event
  event_type: flic_click
  event_data:
    button_name: flic_80e4da72aba3
    click_type: single
action:
  service: notify.notify
  data:
    message: "Flic Turquoise Single"
    title: "Button!"
