# Implicitly attached to toggle master bedroom ceiling

alias: master_bedroom Button 1 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.master_bedroom
    scene_id: 16
action:
  service: notify.notify
  data:
    message: "master_bedroom Button 1 Single"
    title: "Button!"
