alias: matans_bedroom Button 1 Hold
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.matans_bedroom
    scene_id: 12
action:
  service: notify.notify
  data:
    message: "matans_bedroom Button 1 Hold"
    title: "Button!"
