alias: bathroom Button 2 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.bathroom
    scene_id: 24
action:
  # - service: notify.notify
  #   data:
  #     message: "bathroom Button 2 Double"
  #     title: "Button!"
  - service: light.toggle
    entity_id: light.hall
