alias: bathroom Button 2 Triple
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.bathroom_switch
    scene_id: 25
action:
  service: notify.notify
  data:
    message: "bathroom Button 2 Triple"
    title: "Button!"
