alias: bathroom Button 2 Triple
trigger:
  platform: event
  event_type: ozw.scene_activated
  event_data:
    node_id: 13
    scene_id: 25
action:
  - service: light.toggle
    entity_id: light.stairs
