alias: bathroom Button 2 Triple
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.bathroom
    scene_id: 25
action:
  - service: light.toggle
    entity_id: light.stairs