alias: ensuite Button 1 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.ensuite
    scene_id: 14
action:
  - service: fan.toggle
    entity_id: fan.ensuite_extractor