alias: Ensuite Button 1 full during day
trigger:
  platform: time
  at: "06:00:00"
action:
  service: zwave_mqtt.set_config_parameter
  data_template:
    node_id: "{{ state_attr('light.ensuite', 'node_id') }}"
    parameter: 19
    value: 99
