alias: Ensuite Button 1 dim at night
trigger:
  platform: time
  at: "22:00:00"
action:
  service: zwave_mqtt.set_config_parameter
  data_template:
    node_id: "{{ state_attr('zwave.ensuite', 'node_id') }}"
    parameter: 19
    value: 3
