alias: landing Button 2 Triple
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.landing_switch
    scene_id: 25
action:
  service: notify.notify
  data:
    message: "landing Button 2 Triple"
    title: "Button!"
