alias: Button 1 Many
trigger:
  platform: state
  entity_id: sensor.button1_click
  to: many # Triggered on at least 5 clicks
action:
  service: telegram_bot.send_message
  data:
    message: "Button 1 many"
    title: "Button 1 many"
