alias: Button 1 Single
trigger:
  platform: state
  entity_id: sensor.button1_click
  to: single
action:
  service: telegram_bot.send_message
  data:
    message: "Button 1 Single"
    title: "Button 1 Single"
