alias: Button 1 Triple
trigger:
  platform: state
  entity_id: sensor.button1_click
  to: triple
action:
  service: telegram_bot.send_message
  data:
    message: "Button 1 Triple"
    title: "Button 1 Triple"
