alias: bedroom_3 Button 2 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.bedroom_3_switch
    scene_id: 24
action:
  service: notify.notify
  data:
    message: "bedroom_3 Button 2 Double"
    title: "Button!"
