alias: bedroom_3 Button 2 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.bedroom_3_switch
    scene_id: 26
action:
  service: notify.notify
  data:
    message: "bedroom_3 Button 2 Single"
    title: "Button!"
