alias: Button 3 brightness down # hold off
trigger:
  platform: state
  entity_id: sensor.button3_click
  to: brightness_down
action:
  service: telegram_bot.send_message
  data:
    message: "Button 3 brightness down"
    title: "Button 3 brightness down"
