alias: Button 3 brightness up # hold on
trigger:
  platform: state
  entity_id: sensor.button3_click
  to: brightness_up
action:
  service: telegram_bot.send_message
  data:
    message: "Button 3 brightness up"
    title: "Button 3 brightness up"
