alias: playroom Button 1 Double
trigger:
  platform: event
  event_type: zwave_mqtt.scene_activated
  event_data:
    node_id: 6
    scene_id: 14
action:
  - service: light.toggle
    entity_id: light.lamp
