alias: playroom Button 1 Double
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.playroom
    scene_id: 14
action:
  - service: light.toggle
    entity_id: light.lamp
