# Implicitly attached to toggle playroom ceiling
alias: playroom Button 1 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.playroom
    scene_id: 16
action:
  service: notify.notify
  data:
    message: "playroom Button 1 Single"
    title: "Button!"
