alias: Button 2 Double
trigger:
  platform: state
  entity_id: sensor.button2_click
  to: double
action:
  service: telegram_bot.send_message
  data:
    message: "Button 2 Double"
    title: "Button 2 Double"
