alias: Button 2 Many
trigger:
  platform: state
  entity_id: sensor.button2_click
  to: many # Triggered on at least 5 clicks
action:
  service: telegram_bot.send_message
  data:
    message: "Button 2 many"
    title: "Button 2 many"
