alias: Button 2 Quadruple
trigger:
  platform: state
  entity_id: sensor.button2_click
  to: quadruple
action:
  service: telegram_bot.send_message
  data:
    message: "Button 2 Quadruple"
    title: "Button 2 Quadruple"
