alias: Button 2 Single
trigger:
  platform: state
  entity_id: sensor.button2_click
  to: single
action:
  service: telegram_bot.send_message
  data:
    message: "Button 2 Single"
    title: "Button 2 Single"
