alias: Button 2 Triple
trigger:
  platform: state
  entity_id: sensor.button2_click
  to: triple
action:
  service: telegram_bot.send_message
  data:
    message: "Button 2 Triple"
    title: "Button 2 Triple"
