# # Implicitly attached to toggle bathroom ceiling
# alias: bathroom Button 1 Single
# trigger:
#   platform: event
#   event_type: zwave.scene_activated
#   event_data:
#     entity_id: zwave.bathroom
#     scene_id: 16
# action:
#   service: notify.notify
#   data:
#     message: "bathroom Button 1 Single"
#     title: "Button!"

alias: Bathroom Button 1 dim at night
trigger:
  platform: time
  at: '21:00:00'
action:
  service: zwave.set_config_parameter
  data_template:
    node_id: "{{ state_attr('zwave.bathroom', 'node_id') }}"
    parameter: 19
    value: 5

alias: Bathroom Button 1 full during day
trigger:
  platform: time
  at: '06:00:00'
action:
  service: zwave.set_config_parameter
  data_template:
    node_id: "{{ state_attr('zwave.bathroom', 'node_id') }}"
    parameter: 19
    value: 99