alias: landing Button 2 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.landing
    scene_id: 26
action:
  - service: light.toggle
    entity_id: light.hall
