- platform: mqtt
  name: Kitchen Worktop
  state_topic: kitchen-worktop-lights/relay/0
  command_topic: kitchen-worktop-lights/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: kitchen-worktop-lights/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: kitchen-worktop-lights/channel/4
  brightness_command_topic: kitchen-worktop-lights/channel/4/set