substitutions:
  devicename: sonoff_towel

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename}_tmp

logger:
api:
ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename}_button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: ${devicename}_status

switch:
  - platform: gpio
    name: ${devicename}_switch
    pin: GPIO12
    id: relay
