alias: Friday Shabbat In Lights on
trigger:
  - platform: state
    entity_id: binary_sensor.shabbat
    from: 'off'
    to: 'on'
action:
  - service: script.turn_on
    entity_id:
      - script.friday_night_shabbat_in
      - script.bedroom_light_off