alias: Friday Night All Off
trigger:
  - platform: time
    at: "23:59:00"
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - fri
action:
  service: light.turn_off
  entity_id:
    - group.all_lights