homeassistant:

# Example configuration.yaml entry
sensor:
  - platform: imap_email_content
    server: imap.gmail.com
    port: 993
    username: !secret gmail_username
    password: !secret gmail_otp
    senders:
      - noreply@texe.com
    value_template: >-
      {% if 'Your House Alarm Front Door Open' in body %}
        alarm_door_front_open
      {% elif 'Your House Alarm Front Door Closed' in body %}
        alarm_door_front_closed
      {% endif %}

binary_sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: "Front Door"
        entity_id: sensor.alarm_email
        device_class: door
        value_template: >-
          {{ is_state('sensor.alarm_email', 'alarm_door_front_open') }}
