homeassistant:

automation:
  - alias: Alarm full armed notify phone
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house_alarm
        to: armed_full
    action:
      - service: notify.mobile_app_anthony_phone
        data:
          title: Alarm
          message: Full Armed
          data:
            actions:
              - action: all_lights_off
                title: All Lights Off

  - alias: Alarm full armed all lights off
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: all_lights_off
    action:
      - service: script.turn_on
        data:
          entity_id:
            - script.all_lights_off
      - delay: "00:01:00" # delay and then repeat this as zwave is flakey
      - service: script.turn_on
        data:
          entity_id:
            - script.all_lights_off
