homeassistant:

camera:
  - platform: onvif
    host: 192.168.1.204
    name: Front Left
    username: !secret cctv_username
    password: !secret cctv_password
    port: 80
  - platform: onvif
    host: 192.168.1.205
    name: Front Right
    username: !secret cctv_username
    password: !secret cctv_password
    port: 80
  - platform: onvif
    host: 192.168.1.206
    name: Front Door
    username: !secret cctv_username
    password: !secret cctv_password
    port: 80
  - platform: onvif
    host: 192.168.1.207
    name: Rear Left
    username: !secret cctv_username
    password: !secret cctv_password
    port: 80
  - platform: onvif
    host: 192.168.1.208
    name: Rear Kitchen
    username: !secret cctv_username
    password: !secret cctv_password
    port: 80

binary_sensor:
  - platform: hikvision
    name: Front Door
    host: 192.168.1.206
    username: !secret cctv_username
    password: !secret cctv_password
  - platform: hikvision
    name: Front Left
    host: 192.168.1.204
    username: !secret cctv_username
    password: !secret cctv_password
  - platform: hikvision
    name: Front Right
    host: 192.168.1.205
    username: !secret cctv_username
    password: !secret cctv_password
  - platform: hikvision
    name: Rear Left
    host: 192.168.1.207
    username: !secret cctv_username
    password: !secret cctv_password
  - platform: hikvision
    name: Rear Kitchen
    host: 192.168.1.208
    username: !secret cctv_username
    password: !secret cctv_password

  - platform: template
    sensors:
      cctv_front_left:
        friendly_name: CCTV Front Left
        device_class: connectivity
        value_template: "{{ is_state('device_tracker.cctv_front_left', 'home') }}"
      cctv_front_right:
        friendly_name: CCTV Front Right
        device_class: connectivity
        value_template: "{{ is_state('device_tracker.cctv_front_right', 'home') }}"
      cctv_front_door:
        friendly_name: CCTV Front Door
        device_class: connectivity
        value_template: "{{ is_state('device_tracker.cctv_front_door', 'home') }}"
      cctv_rear_left:
        friendly_name: CCTV Rear Left
        device_class: connectivity
        value_template: "{{ is_state('device_tracker.cctv_rear_left', 'home') }}"
      cctv_rear_kitchen:
        friendly_name: CCTV Rear Kitchen
        device_class: connectivity
        value_template: "{{ is_state('device_tracker.cctv_rear_kitchen', 'home') }}"