homeassistant:

binary_sensor:
  - platform: mqtt
    name: Doorbell
    state_topic: "stat/sonoff_doorbell/POWER"

switch:
  - platform: command_line
    switches:
      doorbell_mute:
        command_on: curl http://192.168.1.216/cm?cmnd=event%20doorbell=0
        command_off: curl http://192.168.1.216/cm?cmnd=event%20doorbell=1

automation:
- alias: Doorbell notify phone
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
    - service: notify.notify
      data:
        title: "Doorbell!"
        message: "Ding Dong"
    - service: camera.snapshot
      data:
        entity_id: camera.front_left
        filename: '/config/www/snapshot_{{ entity_id.entity_id }}.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.front_right
        filename: '/config/www/snapshot_{{ entity_id.entity_id }}.jpg'
    - service: notify.pushbullet
      data:
        title: "Ding Dong!"
        message: "Front Right"
        data:
          file: /config/www/snapshot_camera.front_right.jpg
    - service: notify.pushbullet
      data:
        title: "Ding Dong!"
        message: "Front Left"
        data:
          file: /config/www/snapshot_camera.front_left.jpg