homeassistant:

automation:
  - alias: Doorbell notify phone
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell
      to: "on"
    action:
      - service: telegram_bot.send_message
        data:
          title: Doorbell
          message: "https://hillersdon.anthonyangel.co.uk/lovelace/cctv_front"
          parse_mode: html
      - service: telegram_bot.send_photo
        data:
          url: "https://hillersdon.anthonyangel.co.uk{{ states.camera.front_door.attributes.entity_picture }}"
          disable_notification: yes
      - service: telegram_bot.send_photo
        data:
          url: "https://hillersdon.anthonyangel.co.uk{{ states.camera.front_left.attributes.entity_picture }}"
          disable_notification: yes
      - service: telegram_bot.send_photo
        data:
          url: "https://hillersdon.anthonyangel.co.uk{{ states.camera.front_right.attributes.entity_picture }}"
          disable_notification: yes

  - alias: Doorbell show on Lounge Display
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell
      to: "on"
    action:
      - service: camera.play_stream
        data:
          entity_id: camera.front_door
          media_player: media_player.lounge_display
      - delay:
          seconds: 60
      - service: media_player.turn_off
        entity_id: media_player.lounge_display

  - alias: Doorbell notify Lounge TV
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell
      to: "on"
    condition:
      - condition: state
        entity_id: media_player.lounge_tv
        state: "on"
    action:
      - service: notify.lounge_tv
        data:
          message: "Doorbell!"

  - alias: Doorbell notify Kitchen TV
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell
      to: "on"
    condition:
      - condition: state
        entity_id: media_player.kitchen_tv
        state: "on"
    action:
      - service: notify.kitchen_tv
        data:
          message: "Doorbell!"
