homeassistant:
  customize:
    light.external_rear:
      icon: mdi:spotlight
    light.front_door:
      icon: mdi:door

light:
  - platform: mqtt
    name: External Rear
    state_topic: "stat/sonoff_4ch_utility/POWER1"
    command_topic: "cmnd/sonoff_4ch_utility/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: Front Door
    state_topic: "stat/sonoff_4ch_utility/POWER2"
    command_topic: "cmnd/sonoff_4ch_utility/POWER2"
    payload_on: "ON"
    payload_off: "OFF"

automation:
  - alias: Outside front lights on at sunset
    trigger:
      platform: sun
      event: sunset
      offset: "-00:05:00"
    action:
      service: light.turn_on
      entity_id: light.front_door

  - alias: Outside front lights off between 23 - 00
    trigger:
      platform: time
      at: '23:00:00'
    action:
      - delay: '00:{{ (range(0, 59)|random|int) }}:00'
      - service: light.turn_off
        entity_id: light.front_door
