homeassistant:

fan:
  - platform: mqtt
    name: En-Suite
    state_topic: "stat/sonoff_4ch_loft/POWER1"
    command_topic: "cmnd/sonoff_4ch_loft/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: Bathroom
    state_topic: "stat/sonoff_4ch_loft/POWER2"
    command_topic: "cmnd/sonoff_4ch_loft/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: Utility
    state_topic: "stat/sonoff_4ch_utility/POWER3"
    command_topic: "cmnd/sonoff_4ch_utility/POWER3"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: Toilet
    state_topic: "stat/sonoff_basic_toilet/POWER"
    command_topic: "cmnd/sonoff_basic_toilet/POWER"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: template
    fans:
      extractor:
        friendly_name: Extractor
        turn_on:
          service: ifttt.trigger
          data: {"event": "hood_fan_on"}
        turn_off:
          service: ifttt.trigger
          data: {"event": "hood_fan_off"}

automation:
  - alias: Utility Extractor Humidity On
    trigger:
      platform: numeric_state
      entity_id: sensor.utility_humidity
      above: 75
    action:
      service: fan.turn_on
      entity_id: fan.utility
  - alias: Utility Extractor Humidity Off
    trigger:
      platform: numeric_state
      entity_id: sensor.utility_humidity
      below: 75
    action:
      service: fan.turn_off
      entity_id: fan.utility

  - alias: Toilet Extractor Humidity On
    trigger:
      platform: numeric_state
      entity_id: sensor.toilet_humidity
      above: 75
    action:
      service: fan.turn_on
      entity_id: fan.toilet
  - alias: Toilet Extractor Humidity Off
    trigger:
      platform: numeric_state
      entity_id: sensor.toilet_humidity
      below: 75
    action:
      service: fan.turn_off
      entity_id: fan.toilet

  - alias: Ensuite Extractor Humidity On
    trigger:
      platform: numeric_state
      entity_id: sensor.ensuite_humidity
      above: 75
    action:
      service: fan.turn_on
      entity_id: fan.ensuite
  - alias: Ensuite Extractor Humidity Off
    trigger:
      platform: numeric_state
      entity_id: sensor.ensuite_humidity
      below: 75
    action:
      service: fan.turn_off
      entity_id: fan.ensuite

  - alias: Bathroom Extractor Humidity On
    trigger:
      platform: numeric_state
      entity_id: sensor.bathroom_humidity
      above: 75
    action:
      service: fan.turn_on
      entity_id: fan.bathroom
  - alias: Bathroom Extractor Humidity Off
    trigger:
      platform: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 75
    action:
      service: fan.turn_off
      entity_id: fan.bathroom

group:
  extractor_humidity_automations:
    name: Extractor Humidity Automations
    entities:
      - automation.utility_extractor_humidity_on
      - automation.utility_extractor_humidity_off
      - automation.toilet_extractor_humidity_on
      - automation.toilet_extractor_humidity_off
      - automation.ensuite_extractor_humidity_on
      - automation.ensuite_extractor_humidity_off
      - automation.bathroom_extractor_humidity_on
      - automation.bathroom_extractor_humidity_off
