homeassistant:

automation:
  - alias: Utility Extractor Humidity On
    trigger:
      platform: numeric_state
      entity_id: sensor.utility_humidity
      above: 75
    action:
      service: fan.turn_on
      entity_id: fan.sonoff_utility_extractor
  - alias: Utility Extractor Humidity Off
    trigger:
      platform: numeric_state
      entity_id: sensor.utility_humidity
      below: 75
    action:
      service: fan.turn_off
      entity_id: fan.sonoff_utility_extractor

  - alias: Toilet Extractor Humidity On
    trigger:
      platform: numeric_state
      entity_id: sensor.toilet_humidity
      above: 75
    action:
      service: fan.turn_on
      entity_id: fan.sonoff_toilet_extractor
  - alias: Toilet Extractor Humidity Off
    trigger:
      platform: numeric_state
      entity_id: sensor.toilet_humidity
      below: 75
    action:
      service: fan.turn_off
      entity_id: fan.sonoff_toilet_extractor

  - alias: Ensuite Extractor Humidity On
    trigger:
      platform: numeric_state
      entity_id: sensor.ensuite_humidity
      above: 75
    action:
      service: fan.turn_on
      entity_id: fan.sonoff_ensuite_extractor
  - alias: Ensuite Extractor Humidity Off
    trigger:
      platform: numeric_state
      entity_id: sensor.ensuite_humidity
      below: 75
    action:
      service: fan.turn_off
      entity_id: fan.sonoff_ensuite_extractor

  - alias: Bathroom Extractor Humidity On
    trigger:
      platform: numeric_state
      entity_id: sensor.bathroom_humidity
      above: 75
    action:
      service: fan.turn_on
      entity_id: fan.sonoff_bathroom_extractor
  - alias: Bathroom Extractor Humidity Off
    trigger:
      platform: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 75
    action:
      service: fan.turn_off
      entity_id: fan.sonoff_bathroom_extractor

group:
  extractor_humidity_automations:
    name: Extractor Humidity Automations
    entities:
      - automation.utility_extractor_humidity_on
      - automation.utility_extractor_humidity_off
      - automation.toilet_extractor_humidity_on
      - automation.toilet_extractor_humidity_off
      - automation.ensuite_extractor_humidity_on
      - automation.ensuite_extractor_humidity_off
      - automation.bathroom_extractor_humidity_on
      - automation.bathroom_extractor_humidity_off
