homeassistant:
  customize:
    binary_sensor.flic_80e4da72b83e:
      friendly_name: Flic Green
    binary_sensor.flic_80e4da7291ec:
      friendly_name: Flic Black
    binary_sensor.flic_80e4da72aafa:
      friendly_name: Flic White
    binary_sensor.flic_80e4da72aba3:
      friendly_name: Flic Turquoise

binary_sensor:
  - platform: flic

group:
 flic:
   name: Flic Buttons
   entities:
     - binary_sensor.flic_80e4da72b83e
     - binary_sensor.flic_80e4da7291ec
     - binary_sensor.flic_80e4da72aafa
     - binary_sensor.flic_80e4da72aba3