homeassistant:
  customize_glob:
    light.floodlight_*:
      icon: mdi:track-light
    switch.floodlight_*:
      hidden: true

light:
  - platform: switch
    name: Driveway
    entity_id: switch.floodlight_driveway
  - platform: switch
    name: Floodlight Rear Kitchen
    entity_id: switch.floodlight_rear_kitchen
  - platform: switch
    name: Floodlight Rear Lounge 
    entity_id: switch.floodlight_rear_lounge