homeassistant:
  customize_glob:
    light.floodlight_*:
      icon: mdi:track-light
    switch.floodlight_*:
      hidden: true

light:
  - platform: switch
    name: Floodlight Driveway
    entity_id: switch.floodlight_driveway
  - platform: switch
    name: Floodlight Rear Kitchen
    entity_id: switch.floodlight_rear_kitchen
  - platform: switch
    name: Floodlight Rear Lounge
    entity_id: switch.floodlight_rear_lounge

binary_sensor:
  - platform: template
    sensors:
      motion_pir_rear_lounge:
        friendly_name: "Motion Rear Lounge"
        device_class: motion
        value_template: >-
          {{ is_state('sensor.pir_rear_lounge_motion','8') }}
      motion_pir_rear_kitchen:
        friendly_name: "Motion Rear Kitchen"
        device_class: motion
        value_template: >-
          {{ is_state('sensor.pir_rear_kitchen_motion','8') }}
      motion_pir_driveway:
        friendly_name: "Motion Driveway"
        device_class: motion
        value_template: >-
          {{ is_state('sensor.pir_driveway_motion','8') }}
