homeassistant:
  customize:
    light.kitchen_front:
      hidden: true
    light.kitchen_rear:
      hidden: true

light:
  - platform: group
    name: Kitchen Ceiling
    entities:
      - light.kitchen_front
      - light.kitchen_rear