homeassistant:
  customize:
    light.lamp:
      icon: mdi:desk-lamp

binary_sensor:
- platform: template
  sensors:
    playroom_lamp:
      friendly_name: Playroom Lamp
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.lifx_color_1000', 'home') }}"
