homeassistant:
  customize:
    light.lamp_matan:
      icon: mdi:lamp

input_datetime:
  matan_lamp_on:
    name: Matan Lamp On Time
    has_time: true
    has_date: false
    icon: mdi:timer
  matan_lamp_off:
    name: Matan Lamp Off Time
    has_time: true
    has_date: false
    icon: mdi:timer

automation:
  - alias: Matan Button Lamp On Green Toggle
    trigger:
      - platform: state
        entity_id: sensor.button1_click
        to: single
    condition:
      - condition: state
        entity_id: light.lamp_matan
        state: "off"
    action:
      - service: light.turn_on
        entity_id: light.lamp_matan
        data:
          brightness_pct: 100
          color_name: green

  - alias: Matan Button Lamp Off Toggle
    trigger:
      - platform: state
        entity_id: sensor.button1_click
        to: single
    condition:
      - condition: state
        entity_id: light.lamp_matan
        state: "on"
    action:
      - service: light.turn_off
        entity_id: light.lamp_matan

  - alias: Matan Lamp On Timer
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == ((state_attr('input_datetime.matan_lamp_on', 'timestamp') | int ) | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: light.turn_on
        entity_id: light.lamp_matan
        data:
          brightness_pct: 100
          color_name: purple

  - alias: Matan Lamp Off Timer
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == ((state_attr('input_datetime.matan_lamp_off', 'timestamp') | int ) | timestamp_custom('%H:%M', False)) }}"
    action:
      - service: light.turn_off
        entity_id: light.lamp_matan
