homeassistant:

automation:
- alias: Front Door Motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_pir_driveway
    to: 'on'
  action:
    - service: notify.html5_anthony_phone
      data:
        title: "Front Door Motion!"
        message: "Motion"
    - service: camera.snapshot
      data:
        entity_id: camera.front_door
        filename: '/config/www/snapshot_{{ entity_id.entity_id }}.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.front_left
        filename: '/config/www/snapshot_{{ entity_id.entity_id }}.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.front_right
        filename: '/config/www/snapshot_{{ entity_id.entity_id }}.jpg'
    - service: notify.gmail_anthony
      data:
          title: 'Motion'
          message: "There was Front Door Motion at {{now().strftime('%H:%M') }}"
          data:
              images:              
                  - /config/www/snapshot_camera.front_door.jpg
                  - /config/www/snapshot_camera.front_right.jpg
                  - /config/www/snapshot_camera.front_left.jpg
