homeassistant:
  customize_glob:
    binary_sensor.*_nest_protect_online:
      icon: mdi:smoke-detector

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

  sensors:
    monitored_conditions:
      - "co_status"
      - "smoke_status"
      - "color_status"
