homeassistant:
  customize_glob:
    binary_sensor.*_nest_protect_online:
      icon: mdi:smoke-detector

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

  sensors:
    monitored_conditions:
      - 'co_status'
      - 'smoke_status'
      - 'color_status'

binary_sensor:
  - platform: template
    sensors:
      nest_emergency:
        friendly_name: Nest Emergency
        device_class: safety
        value_template: >-
          {{not is_state('sensor.hallway_nest_protect_color_status', 'green')
             or not is_state('sensor.kitchen_nest_protect_color_status', 'green')
             or not is_state('sensor.loft_nest_protect_color_status', 'green')
             or not is_state('sensor.upstairs_nest_protect_color_status', 'green') }}