homeassistant:
  customize_glob:
    binary_sensor.*_nest_protect_online:
      icon: mdi:smoke-detector
#    sensor.*_nest_protect_battery_health:
#      icon: mdi:battery

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

  sensors:
    monitored_conditions:
      - 'co_status'
      - 'smoke_status'
  #    - 'battery_health'
      - 'color_status'

group:
  smoke:
    name: Smoke
    entities:
      - sensor.hallway_nest_protect_smoke_status
      - sensor.kitchen_nest_protect_smoke_status
      - sensor.loft_nest_protect_smoke_status
      - sensor.upstairs_nest_protect_smoke_status

  co:
    name: CO
    entities:
      - sensor.hallway_nest_protect_co_status
      - sensor.kitchen_nest_protect_co_status
      - sensor.loft_nest_protect_co_status
      - sensor.upstairs_nest_protect_co_status

  nest_protect_online:
    name: Nest Protect Online
    entities:
      - binary_sensor.hallway_nest_protect_online
      - binary_sensor.kitchen_nest_protect_online
      - binary_sensor.loft_nest_protect_online
      - binary_sensor.upstairs_nest_protect_online

  # nest_protect_battery:
  #   name: Nest Protect Battery
  #   entities:
  #     - sensor.hallway_nest_protect_battery_health
  #     - sensor.kitchen_nest_protect_battery_health
  #     - sensor.loft_nest_protect_battery_health
  #     - sensor.upstairs_nest_protect_battery_health

  nest_protect_colour:
    name: Nest Protect Colour
    entities:
      - sensor.hallway_nest_protect_color_status
      - sensor.kitchen_nest_protect_color_status
      - sensor.loft_nest_protect_color_status
      - sensor.upstairs_nest_protect_color_status
