homeassistant:
  customize_glob:
    device_tracker.*:
      hidden: true

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    site_id: !secret unifi_site_id

binary_sensor:
- platform: template
  sensors:
  # CCTV
    cctv_front_left:
      friendly_name: CCTV Front Left
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.cctvfrontleft', 'home') }}"
    cctv_front_right:
      friendly_name: CCTV Front Right
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.cctvfrontright', 'home') }}"
    cctv_front_door:
      friendly_name: CCTV Front Door
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.cctvfrontdoor', 'home') }}"
    cctv_rear_1:
      friendly_name: CCTV Rear 1
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.cctvrear1', 'home') }}"
    cctv_rear_2:
      friendly_name: CCTV Rear 2
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.cctvrear2', 'home') }}"
    # Cupboard Devices  
    pdu:
      friendly_name: PDU
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.pdu', 'home') }}"
    texe_hub:
      friendly_name: Texecom Hub
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.texe_hub', 'home') }}"
    nas:
      friendly_name: NAS
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.dlink2a558c', 'home') }}"
    gigabyte:
      friendly_name: Gigabyte
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.gigabyte', 'home') }}"
    # Remote Sonoff (migrating away from this to ESP Home status)
    sonoff_doorbell:
      friendly_name: Sonoff Doorbell
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.sonoffdoorbell', 'home') }}"
    # Kitchen Appliances  
    dishwasher_left:
      friendly_name: Dishwasher Left
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.dishwasher_left', 'home') }}"
    dishwasher_right:
      friendly_name: Dishwasher Right
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.dishwasher_right', 'home') }}"
    oven_left:
      friendly_name: Oven Left
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.oven_left', 'home') }}"
    oven_right:
      friendly_name: Oven Right
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.oven_right', 'home') }}"
    hob:
      friendly_name: Hob
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.hob', 'home') }}"
    extractor:
      friendly_name: Extractor
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.extractor', 'home') }}"
    # Media Players
    google_home_mini:
      friendly_name: Google Home Mini
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.googlehomemini', 'home') }}"
    lounge_tv:
      friendly_name: Lounge TV
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.lounge_tv', 'home') }}"
    kitchen_tv:
      friendly_name: Kitchen TV
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.kitchen_tv', 'home') }}"
    lounge_chromecast:
      friendly_name: Lounge Chromecast
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.lounge_chromecast', 'home') }}"
    kitchen_chromecast:
      friendly_name: Kitchen Chromecast
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.kitchen_chromecast', 'home') }}"
    sonos_kitchen:
      friendly_name: Sonos Kitchen
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.sonos_kitchen', 'home') }}"
    sonos_bedroom:
      friendly_name: Sonos Bedroom
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.sonos_bedroom', 'home') }}"
    sonos_lounge:
      friendly_name: Sonos Lounge
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.sonos_lounge', 'home') }}"
    sonos_matan:
      friendly_name: Sonos Matan
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.sonos_matan', 'home') }}"
    sonos_playroom:
      friendly_name: Sonos Playroom
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.sonos_playroom', 'home') }}"
    # Misc Lights 
    playroom_lamp:
      friendly_name: Playroom Lamp
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.lifx_color_1000', 'home') }}"      

group:
 network_devices:
   name: Network Devices
   entities:
     - binary_sensor.cctv_front_left
     - binary_sensor.cctv_front_right
     - binary_sensor.cctv_front_door
     - binary_sensor.cctv_rear_1
     - binary_sensor.cctv_rear_2
     - binary_sensor.hassio
     - binary_sensor.nest_hallway
     - binary_sensor.nest_kitchen
     - binary_sensor.nest_loft
     - binary_sensor.nest_upstairs
     - binary_sensor.pdu
     - binary_sensor.sonoff_doorbell
     - binary_sensor.kitchen_island_lights
     - binary_sensor.kitchen_worktop_lights
     - binary_sensor.tado_bridge
     - binary_sensor.texe_hub
     - binary_sensor.dishwasher_left
     - binary_sensor.dishwasher_right
     - binary_sensor.oven_left
     - binary_sensor.oven_right
     - binary_sensor.hob
     - binary_sensor.extractor
     - binary_sensor.google_home_mini
     - binary_sensor.lounge_tv
     - binary_sensor.kitchen_tv
     - binary_sensor.playroom_lamp
     - binary_sensor.nas
     - binary_sensor.lounge_chromecast
     - binary_sensor.kitchen_chromecast
     - binary_sensor.gigabyte
     - binary_sensor.sonos_kitchen
     - binary_sensor.sonos_bedroom
     - binary_sensor.sonos_lounge
     - binary_sensor.sonos_matan
     - binary_sensor.sonos_playroom
     - binary_sensor.toy_kitchen_worktop_lights

