homeassistant:

  device_tracker:
    - platform: unifi
      host: !secret unifi_host
      username: !secret unifi_username
      password: !secret unifi_password
      verify_ssl: false
      site_id: !secret unifi_site_id