homeassistant:
  customize_glob:
    device_tracker.cctv*:
      hidden: true
    device_tracker.nest*:
      hidden: true
    device_tracker.sonoff*:
      hidden: true

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    site_id: !secret unifi_site_id

binary_sensor:
- platform: template
  sensors:
    cctv_front_left:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.cctvfrontleft', 'home') }}"
    cctv_front_right:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.cctvfrontright', 'home') }}"
    hassio:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.hassio', 'home') }}"
    nest_hallway:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.nest_hallway', 'home') }}"
    nest_kitchen:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.nest_kitchen', 'home') }}"
    nest_loft:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.nest_loft', 'home') }}"
    nest_upstairs:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.nest_upstairs', 'home') }}"
    pdu:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.pdu', 'home') }}"
    sonoff_4ch_utility:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.sonoff4chutility', 'home') }}"
    tado_bridge:
      device_class: connectivity
      value_template: "{{ is_state('device_tracker.tado', 'home') }}"

group:
 network_devices:
   name: Network Devices
   entities:
     - binary_sensor.cctv_front_left
     - binary_sensor.cctv_front_right
     - binary_sensor.hassio
     - binary_sensor.nest_hallway
     - binary_sensor.nest_kitchen
     - binary_sensor.nest_loft
     - binary_sensor.nest_upstairs
     - binary_sensor.pdu
     - binary_sensor.sonoff_4ch_utility
     - binary_sensor.tado_bridge

