homeassistant:
  customize:
    switch.pdu_port_1:
      icon: mdi:power-socket
    switch.pdu_port_2:
      icon: mdi:power-socket
    switch.pdu_port_3:
      icon: mdi:power-socket
    switch.pdu_port_4:
      icon: mdi:power-socket
    switch.pdu_port_5:
      icon: mdi:power-socket
    switch.pdu_port_6:
      icon: mdi:power-socket
    switch.pdu_port_7:
      icon: mdi:power-socket
    switch.pdu_port_8:
      icon: mdi:power-socket
    switch.pdu_port_9:
      icon: mdi:power-socket

switch:
  - platform: snmp
    name: PDU Port 1
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.1
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 2
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.2
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 3
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.3
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 4
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.4
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 5
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.5
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 7
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.7
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 6
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.6
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 7
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.7
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 7
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.7
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 8
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.8
    payload_on: 1
    payload_off: 2
  - platform: snmp
    name: PDU Port 9
    host: 192.168.1.118
    baseoid: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.9
    payload_on: 1
    payload_off: 2

group:
  pdu:
    name: PDU
    entities:
      - switch.pdu_port_1
      - switch.pdu_port_2
      - switch.pdu_port_3
      - switch.pdu_port_4
      - switch.pdu_port_5
      - switch.pdu_port_6
      - switch.pdu_port_7
      - switch.pdu_port_8
      - switch.pdu_port_9
      
