homeassistant:
  customize_glob:
    light.floodlight_*:
      icon: track-light
    switch.floodlight_*:
      hidden: true

light:
  - platform: 
    name: Rear Kitchen Floodlight
    entity_id: switch.floodlight_rear_kitchen
  - platform: 
    name: Rear Lounge Floodlight
    entity_id: switch.floodlight_rear_lounge