homeassistant:
  customize_glob:
    sensor.*_overlay:
      hidden: true
    sensor.*_power:
      hidden: true
    sensor.*_link:
      hidden: true
    sensor.*_mode:
      hidden: true
    sensor.hillersdon_tado_bridge_status:
      hidden: true

tado:
  username: !secret tado_username
  password: !secret tado_password

binary_sensor:
  - platform: template
    sensors:
      tado_bridge_status:
        friendly_name: Tado Bridge Status
        device_class: connectivity
        value_template: "{{ is_state('sensor.hillersdon_tado_bridge_status', 'True') }}"

group:
  humidity:
    name: Humidity
    icon: mdi:water-percent
    entities:
      - sensor.bedroom_master_humidity
      - sensor.bedroom_matan_humidity
      - sensor.3rd_bedroom_humidity
      - sensor.4th_bedroom_humidity
      - sensor.ensuite_humidity
      - sensor.hall_humidity
      - sensor.landing_humidity
      - sensor.kitchen_humidity
      - sensor.lounge_humidity
      - sensor.office_humidity
      - sensor.playroom_humidity
      - sensor.toilet_humidity
      - sensor.utility_humidity
      - sensor.bathroom_humidity

  temperature:
    name: Temperature
    icon: mdi:thermometer
    entities:
      - sensor.bedroom_master_temperature
      - sensor.bedroom_matan_temperature
      - sensor.3rd_bedroom_temperature
      - sensor.4th_bedroom_temperature
      - sensor.ensuite_temperature
      - sensor.hall_temperature
      - sensor.landing_temperature
      - sensor.kitchen_temperature
      - sensor.lounge_temperature
      - sensor.office_temperature
      - sensor.playroom_temperature
      - sensor.toilet_temperature
      - sensor.utility_temperature
      - sensor.bathroom_temperature

  heating:
    name: Heating
    icon: mdi:radiator
    entities:
      - sensor.bedroom_master_heating
      - sensor.bedroom_matan_heating
      - sensor.3rd_bedroom_heating
      - sensor.4th_bedroom_heating
      - sensor.ensuite_heating
      - sensor.hall_heating
      - sensor.landing_heating
      - sensor.kitchen_heating
      - sensor.lounge_heating
      - sensor.office_heating
      - sensor.playroom_heating
      - sensor.toilet_heating
      - sensor.utility_heating
      - sensor.bathroom_heating
