homeassistant:
  customize_glob:
    sensor.*_overlay:
      hidden: true
    sensor.*_power:
      hidden: true
    sensor.*_link:
      hidden: true
    sensor.*_mode:
      hidden: true
      
group:
  humidity:
    name: Humidity
    icon: mdi:water-percent
    entities:
      - sensor.master_bedroom_humidity
      - sensor.matans_bedroom_humidity
      - sensor.3rd_bedroom_humidity
      - sensor.4th_bedroom_humidity
      - sensor.ensuite_humidity
      - sensor.hall_humidity
      - sensor.landing_humidity
      - sensor.kitchen_humidity
      - sensor.lounge_humidity
      - sensor.office_humidity
      - sensor.playroom_humidity
      - sensor.toilet_humidity
      - sensor.utility_humidity
      - sensor.bathroom_humidity

  temperature:
    name: Temperature
    icon: mdi:thermometer
    entities:
      - sensor.master_bedroom_temperature
      - sensor.matans_bedroom_temperature
      - sensor.3rd_bedroom_temperature
      - sensor.4th_bedroom_temperature
      - sensor.ensuite_temperature
      - sensor.hall_temperature
      - sensor.landing_temperature
      - sensor.kitchen_temperature
      - sensor.lounge_temperature
      - sensor.office_temperature
      - sensor.playroom_temperature
      - sensor.toilet_temperature
      - sensor.utility_temperature
      - sensor.bathroom_temperature

  heating:
    name: Heating
    icon: mdi:radiator
    entities:
      - sensor.master_bedroom_heating
      - sensor.matans_bedroom_heating
      - sensor.3rd_bedroom_heating
      - sensor.4th_bedroom_heating
      - sensor.ensuite_heating
      - sensor.hall_heating
      - sensor.landing_heating
      - sensor.kitchen_heating
      - sensor.lounge_heating
      - sensor.office_heating
      - sensor.playroom_heating
      - sensor.toilet_heating
      - sensor.utility_heating
      - sensor.bathroom_heating