homeassistant:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret anthony_telegram_id

notify:
  - platform: telegram
    chat_id: !secret anthony_telegram_id
