homeassistant:
  customize:
    light.toy_kitchen_worktop:
      icon: mdi:silverware-fork-knife

light:
  - platform: mqtt
    name: Toy Kitchen Worktop
    state_topic: toy-kitchen-worktop/relay/0
    command_topic: toy-kitchen-worktop/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: toy-kitchen-worktop/status
    payload_available: 1
    payload_not_available: 0
    brightness_state_topic: toy-kitchen-worktop/channel/2
    brightness_command_topic: toy-kitchen-worktop/channel/2/set

automation:
- alias: Toy Kitchen Light 10 minute timeout 
  trigger:
    platform: state  
    entity_id: light.toy_kitchen_worktop
    to: 'on'
    for:
      minutes: 10
  action:
  - service: light.turn_off
    entity_id: light.toy_kitchen_worktop