homeassistant:

media_player:

webostv:
  - name: Kitchen TV
    host: 192.168.1.231
    standby_connection: true
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 78:5D:C8:98:58:E7
    customize:
      sources:
        - LiveTV
        - YouTube
        - Chromecast
        - Plex
        - Netflix
        - BBC iPlayer
        - Amazon Prime Video

  - name: Lounge TV
    host: 192.168.1.230
    standby_connection: true
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 14:C9:13:32:3F:B9
    customize:
      sources:
        - LiveTV
        - YouTube
        - Chromecast
        - Plex
        - Netflix
        - BBC iPlayer
        - Amazon Prime Video

notify:

binary_sensor:
  - platform: template
    sensors:
      lounge_tv:
        friendly_name: Lounge TV
        device_class: connectivity
        value_template: "{{ is_state('device_tracker.lounge_tv', 'home') }}"
      kitchen_tv:
        friendly_name: Kitchen TV
        device_class: connectivity
        value_template: "{{ is_state('device_tracker.kitchen_tv', 'home') }}"
