# Linked to a zwave group to toggle master bedroom ceiling
alias: ensuite Button 2 Single
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.ensuite
    scene_id: 26
action:
  - service: notify.notify
    data:
      message: "ensuite Button 2 Single"
      title: "Button!"