alias: ensuite Button 2 Single
trigger:
  platform: event
  event_type: ozw.scene_activated
  event_data:
    node_id: 14
    scene_id: 26
action:
  - service: light.toggle
    entity_id: light.bedroom_master
